### ISSUE TITLE
Crear método y test lower

### ISSUE THREAD

**Issue by RaquelDiazG** [RaquelDiazG/SpaiEcp2RaquelDiaz#10]
Más información sobre su implementación en la [wiki](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/wikiFeatures#decimalcollection)

**Comment by ricardossmadrid** [comment]
Buenas tardes @RaquelDiazG 

Tengo una duda sobre con qué rama comenzar en tu proyecto.

![image](https://cloud.githubusercontent.com/assets/14840911/10269109/be386c92-6acc-11e5-9eb3-3eee1c4de58d.png)

La rama develop, no se encuentra al final de la construcción del proyecto.

¿Parto desde develop igualmente? ¿Prefieres hacer un merge antes de que comencemos? ¿Elimino la rama develop que se crea en mi repositorio local, creo una rama develop a raíz de la master y, al finalizar la tarea hago un push con la rama develop?

Quedo a la espera de tus comentarios.

Muchas gracias y un saludo

**Comment by RaquelDiazG** [comment]
Hola @ricardossmadrid, el otro día actualicé el README e hice el merge, pero se me olvidó poner develop a la misma altura de master para que partan del mismo punto.
Ya lo he arreglado, así que ahora deberías tener las dos ramas a la misma altura.
Gracias por avisar.

**Comment by ricardossmadrid** [comment]
Creada la ampliación para la clase DecimalCollection

**Comment by RaquelDiazG** [comment]
Perfecto
