### ISSUE TITLE
Crear método y test average

### ISSUE THREAD

**Issue by RaquelDiazG** [RaquelDiazG/SpaiEcp2RaquelDiaz#11]
Más información sobre su implementación en la [wiki](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/wiki/Features#decimalcollection)

**Comment by LigiaCano** [comment]
Creado el metodo average y test de la clase DecimalCollection

**Comment by RaquelDiazG** [comment]
Podías haber utilizado el método sum() que ya estaba implementado.
El nombre del test no es correcto. Debería ser "averageTest"
Abro el isuue para que hagas estos cambios en la **rama Release-1.0**.
Gracias.

**Comment by LigiaCano** [comment]
Listo puedes verificar la actualizacion

**Comment by RaquelDiazG** [comment]
Perfecto
