### ISSUE TITLE
Crear método y test isEquivalent

### ISSUE THREAD

**Issue by RaquelDiazG** [RaquelDiazG/SpaiEcp2RaquelDiaz#13]
Más información sobre su implementación en la [wiki](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/wiki/Features#fraction)

**Comment by sermo7** [comment]
Hola de nuevo Raquel,

Para este caso creo que ocurre lo mismo que para lo que te acabo de [poner en la otra tarea](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/issues/16#issuecomment-145378039)... ¿o soy yo el equivocado? Yo creo que se deben introducir dos parámetros en el método no??? Corrígeme si no estoy en lo cierto...

Gracias.

**Comment by RaquelDiazG** [comment]
Hola Sergio.
Mi idea es igual que la anterior.
Comprobar si la fracción actual es equivalente a la que te pasan como parámetro
Un ejemplo de su uso sería el siguiente:

``` javascript
Fraction f1 = new Fraction (1,1);
Fraction f2 = new Fraction (2,3);
boolean is = f1.isEquivalent(f2);
```

Espero haberte aclarado en ambos casos.
Gracias.

**Comment by sermo7** [comment]
Sí, igual que el caso anterior... le estaba dando vueltas a lo que no era!
Gracias por la aclaración igualmente ;)

**Comment by RaquelDiazG** [comment]
Perfecto
