### ISSUE TITLE
Crear método y test isGreater

### ISSUE THREAD

**Issue by RaquelDiazG** [RaquelDiazG/SpaiEcp2RaquelDiaz#14]
Más información sobre su implementación en la [wiki](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/wiki/Features#fraction)

**Comment by LigiaCano** [comment]
Creado el metodo isGreater y el test en la case Fraction

**Comment by RaquelDiazG** [comment]
El nombre del test es incorrecto. Debería ser "isGreaterTest" 
Abro el isuue para que hagas estos cambios en la rama Release-1.0.
Gracias

**Comment by LigiaCano** [comment]
Listo puedes verificar la actualizacion

**Comment by RaquelDiazG** [comment]
Perfecto
