### ISSUE TITLE
Crear método y test sum

### ISSUE THREAD

**Issue by RaquelDiazG** [RaquelDiazG/SpaiEcp2RaquelDiaz#16]
Más información sobre su implementación en la [wiki](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/wiki/Features#point)

**Comment by sermo7** [comment]
Hola Raquel,

Respecto a la creación del método **_sum(Point point)**_ he estado mirando la **[descripción del mismo](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/wiki/Features#formato-de-las-ampliaciones)** y no me queda del todo claro la mejora que quieres realizar... ¿el objetivo del método es sumar dos puntos? Si es así creo que entonces se deberían pasar como parámetro dos puntos en lugar de uno... ¿me lo podrías confirmar?

Gracias.

**Comment by RaquelDiazG** [comment]
Sí, mi idea es que sumes un punto al punto actual.
Un ejemplo de su uso sería el siguiente:

``` javascript
Point p1 = new Point (1,1);
Point p2 = new Point (2,3)
Point nuevoPunto = p1.sum(p2);
//Siendo el nuevoPunto (3,4)
```

Entonces de esta forma solo se le pasa un punto como parámetro.
¿Te parece?

**Comment by sermo7** [comment]
Ahh vale, entendido!!! Yo le estaba dando la vuelta a la tortilla... así que creo que lo otro que te he puesto estamos en las mismas jeje
Gracias por la explicación :)

**Comment by RaquelDiazG** [comment]
Hola Sergio, en el sumTest() no estás probando el funcionamiento del método sum().
Abro el issue para que hagas el cambio en la rama Release-1.0
Gracias.

**Comment by sermo7** [comment]
Modificado sumTest() para utilizar el método sum(). Vuelvo a cerrar el issue.
