### ISSUE TITLE
Crear método y test toUppercase

### ISSUE THREAD

**Issue by RaquelDiazG** [RaquelDiazG/SpaiEcp2RaquelDiaz#18]
Más información sobre su implementación en la [wiki](https://github.com/RaquelDiazG/SpaiEcp2RaquelDiaz/wiki/Features#user)

**Comment by LigiaCano** [comment]
Hola Raquel
Que debo devolver en mayuscula?

**Comment by RaquelDiazG** [comment]
Tienes que devolver el string con el que llaman al método en mayúsculas.
Te dejo un ejemplo de uso:

``` javascript`
User user = new User(1, "Raquel", "Diaz");
String uppercase1 = user.getName().toUppercase(); //Debe devolver "RAQUEL"
String uppercase2 = user.getFamilyName().toUppercase(); //Debe devolver "DIAZ"
```

Espero haberte aclarado.

**Comment by LigiaCano** [comment]
Creado el metodo toUppercase y el test de la clase User

**Comment by RaquelDiazG** [comment]
El nombre del test no es correcto. Debería ser "toUppercaseTest"
Abro el isuue para que hagas estos cambios en la rama Release-1.0.
Gracias.

**Comment by LigiaCano** [comment]
Listo puedes verificar la actualizacion

**Comment by RaquelDiazG** [comment]
Perfecto
